# Application configuration
server:
  port: 8092
spring:
  application:
    name: configuration
  datasource:
    password: ${DATABASE_PASSWORD:ogedik.112233}
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/scrumier?createDatabaseIfNotExist=true
    username: ${DATABASE_USERNAME:root}
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
    show-sql: true

# Cache Properties
cache:
  configuration:
    name: configurationCache
  instanceName: hazelcast-instance

# Eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: http://${DISCOVERY_SERVER_HOST:localhost}:${DISCOVERY_SERVER_PORT:8761}/eureka

# Logging properties
logging:
  level:
    org:
      hibernate:
        stat: debug
        type: trace